In [2]:
import pandas as pd

In [ ]:
df_1 = pd.read_csv("FossilFuelCombustion.csv")
df_2 = pd.read_csv("FossilFuelCombustionBySector.csv")

In [4]:
new_df_1 = pd.DataFrame(df_1.values[1:], columns=df_1.iloc[0])
new_df_1 = new_df_1.dropna()
new_df_1

,Gas,1990.0,1991.0,1992.0,1993.0,1994.0,1995.0,1996.0,1997.0,1998.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,CO2,4752.2,4705.9,4801.4,4917.7,4981.7,5037.8,5215.2,5275.8,5332.3,...,5114.8,5172.9,5002.9,4906.3,4845.1,4988.2,4852.6,4341.7,4654.3,4699.4
1,CH4,16.9,16.9,17.2,16.5,16.3,16.2,16.5,15.4,14.4,...,13.0,13.0,12.5,11.8,11.5,12.5,12.7,10.5,10.6,11.2
2,N2O,60.8,62.1,64.8,67.3,69.7,71.5,73.4,75.0,76.1,...,53.5,51.9,47.9,46.5,44.0,42.8,41.2,36.7,38.9,41.4
3,Total,4829.9,4784.9,4883.4,5001.5,5067.7,5125.5,5305.0,5366.1,5422.8,...,5181.4,5237.8,5063.4,4964.6,4900.6,5043.4,4906.6,4388.9,4703.7,4752.0

In [ ]:
new_df_2 = pd.DataFrame(df_2.values[1:], columns=df_2.iloc[0])
new_df_2 = new_df_2.dropna()
new_df_2

,Fuel/Sector,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Coal,1719.8,1715.8,1733.0,1798.3,1805.0,1820.4,1905.2,1950.5,1979.4,...,1658.0,1654.8,1427.5,1310.8,1270.1,1211.6,1028.1,835.6,957.4,898.8
1,Residential,3.0,2.4,2.5,2.5,2.0,1.7,1.6,1.5,1.1,...,0.0,0.0,0.0,0.0,0.0,NO,NO,NO,NO,NO
2,Commercial,12.0,11.1,11.3,11.3,11.3,11.2,11.6,12.3,8.9,...,3.9,3.8,3.0,2.3,2.0,1.8,1.6,1.4,1.4,1.4
3,Industrial,157.8,154.6,150.3,152.5,153.5,147.2,140.1,140.2,141.8,...,79.5,79.0,69.8,63.2,58.7,54.4,49.4,43.0,43.0,43.0
4,Transportation,NO,NO,NO,NO,NO,NO,NO,NO,NO,...,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
5,Electric Power,1546.5,1547.2,1568.5,1631.6,1637.9,1659.9,1751.5,1796.0,1827.1,...,1571.3,1568.6,1351.4,1242.0,1207.1,1152.9,973.5,788.2,910.1,851.5
6,U.S. Territories,0.5,0.5,0.4,0.4,0.4,0.4,0.4,0.4,0.5,...,3.3,3.4,3.3,3.3,2.3,2.6,3.6,3.1,2.9,2.9
7,Natural Gas,998.6,1020.9,1054.3,1081.8,1106.6,1155.0,1176.3,1182.5,1158.7,...,1390.8,1419.1,1455.4,1461.3,1433.2,1592.0,1649.2,1615.7,1622.1,1706.8
8,Residential,237.8,247.3,254.6,268.2,262.9,262.8,284.0,270.1,246.1,...,266.4,277.7,252.7,238.4,241.5,273.8,275.5,256.4,258.6,272.0
9,Commercial,142.0,148.1,152.1,154.9,157.0,164.2,171.1,174.3,163.3,...,179.2,189.2,175.4,170.5,173.2,192.5,192.9,173.5,180.4,192.3
10,Industrial,407.4,413.6,429.3,437.0,438.2,461.5,477.2,477.9,466.2,...,450.9,465.9,459.6,464.0,468.1,493.5,501.5,489.7,501.2,510.4
11,Transportation,36.0,32.9,32.2,34.2,37.6,38.4,39.1,41.4,35.3,...,47.0,40.2,39.4,40.1,42.3,50.9,58.9,58.7,65.2,70.2
12,Electric Power,175.4,179.0,186.1,187.6,210.9,228.2,204.9,218.8,247.7,...,444.2,442.9,525.2,545.0,505.6,577.9,616.6,634.8,612.8,659.3
13,U.S. Territories,NO,NO,NO,NO,NO,NO,NO,NO,NO,...,3.1,3.2,3.0,3.4,2.5,3.3,3.8,2.6,3.9,2.7
14,Petroleum,2033.3,1968.7,2013.6,2037.0,2069.6,2062.0,2133.2,2142.3,2193.8,...,2065.6,2098.5,2119.7,2133.8,2141.3,2184.2,2174.9,1890.0,2074.4,2093.4
15,Residential,97.8,98.0,96.9,95.4,92.1,88.7,97.9,93.4,84.4,...,62.9,69.1,64.9,54.8,52.5,65.1,67.4,58.4,59.4,62.1
16,Commercial,74.3,73.4,64.6,56.9,56.4,52.4,54.8,51.3,47.9,...,41.2,39.5,66.4,59.1,57.2,52.0,57.2,54.4,55.7,65.1
17,Industrial,311.2,298.5,309.6,301.7,299.2,298.8,309.4,303.7,297.7,...,295.3,275.9,263.5,261.1,253.5,262.6,258.9,229.3,236.3,247.6
18,Transportation,1432.9,1389.5,1445.4,1474.5,1516.4,1542.3,1588.3,1602.1,1643.6,...,1622.0,1667.1,1679.0,1717.8,1738.1,1762.2,1757.7,1514.2,1688.4,1681.1
19,Electric Power,97.5,90.7,75.5,86.4,81.2,58.7,63.4,72.2,101.3,...,22.4,25.3,23.7,21.5,18.9,22.2,16.2,16.2,17.7,20.5
20,U.S. Territories,19.5,18.7,21.6,22.2,24.3,21.1,19.3,19.6,19.0,...,21.8,21.6,22.2,19.5,21.1,20.1,17.5,17.5,17.0,17.0
21,Geothermal a,0.5,0.5,0.5,0.6,0.5,0.4,0.5,0.5,0.5,...,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
22,Electric Power,0.5,0.5,0.5,0.6,0.5,0.4,0.5,0.5,0.5,...,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4
23,Total,4752.2,4705.9,4801.4,4917.7,4981.7,5037.8,5215.2,5275.8,5332.3,...,5114.8,5172.9,5002.9,4906.3,4845.1,4988.2,4852.6,4341.7,4654.3,4699.4